language: cpp
arch: arm64
dist: bionic
compiler: clang
install: skip
script:
- uname -a
- mkdir mmc-develop-arm64 && cd mmc-develop-arm64
- touch testfile
- cd ..
after_success:
- tar -zcf mmc-develop-arm64.tar.gz mmc-develop-arm64
deploy:
  provider: releases
  api_key:
    secure: "jn5sYRLcIyVU4dQjx4ogZJLkxR4xGFw3Z/eW8Hd5Ttf9XPOhjRt7woi3xYA7RdRGZ6ibqvqbk4ZR3jnJGFNqSiH//oko0aZt1dRMgULQyqCV8hR6nyOYZFg/yXo7q24XEiZ4MGfovU2wWU50jx+PlSMHJSJzVC1r1ntugZ0TD2EAO6kVtD+PcYJWnO0knkBpX8l6w1ivkmomExPu/03T2T0P+XNQ78e3XahmQTdeyq7vLHwuAiF2uMNj3BwtZLAF9Afss7lN0NM+mv6SEyj1TOM9lTMxjnwh4K4/WyHB4bDnn2exak/5CUNps5LAExu19Ino7wcKmmcduuqVQyMA+cTP7D23WLUi7jIDeb9cZEi+LgjoKyZ24rSTYp8GQ1A7ofs/LxG+/Mfz1o+Ch3u8BX9as/uB4bRE8/imMWTVslp9mzG8KHaxlgxq3lKizwkbts5P0/JucBsPh+/V/J6OzFqgoGJhh5/fMHIzo6eK7l0unzwYL7JsfsZ4EYlzXT9OSg6pnzPOfkk32flmdx4+dPfSfiUJqt+lbGuOjeoJAvqFhMD7YnkJokDQ/qB9AQcuFPMpk97CvJUXzFQa8eB3KjMYdcfXVDaOjGg245xADHEU5Tm4C06MfFMy5Q9b6FkH9pi/UaZDmgGvpSQCIkesrCYndf0pruQpvAvRScYxBaI="
  file: "mmc-develop-arm64.tar.gz"
  skip_cleanup: 'true'
  draft: true
  on:
    all_branches: true
    repo: JJTech0130/MultiMC5
