language: cpp
arch: arm64
dist: bionic
compiler: clang
install: skip
script:
- uname -a
- mkdir mmc-develop-arm64 && cd mmc-develop-arm64
- touch testfile
- cd ..
after_success:
- tar -zcf mmc-develop-arm64.tar.gz mmc-develop-arm64
deploy:
  provider: releases
  api_key:
    secure: YhuKCXOCqLNBf1cspjOaF/uAj8OOHh+d+cKZkUhvS8uEZ7MAqqM47/kJk1E2A31C4wLaKYjDfGpo/WgMgKXipjaw6I2cnVKlePmfk5ilSR7LdAu9ps5BRru+YSab+GyT9kFJK3K7RLjXjb+VvbeomNhNFm0m66BBfSUj/hfjK5zfdNRxvKgJQvOcU/nx2gJOroMQ9QGRhZXLp2eY1xR2QiXNitUfKALn2o4XGov0ioQvoMSTTNDvXqHc3YymsCnSnLASPcG72YfgmH4c4QUaGYwPoPsUePErUsWI/swC8516df7rHHp4c2UmAPtBLpOdFKkpcgEjSUT8Kl9jBpqU2cRqSydrNFISaQaWa6N1m0m2eOT9uyVXacDV1TqY+Xb/a+ERBWcnj830F+mZ6x9Ifa2SOY3wx4NjsMViLvk7qM4UswmnqhBPr3sH4nPlksEDmJ2j0GfyEUYSTS+JBwxcqntHgBJuxzMbQzhimcmiKF3oXCc1tSWaJScm1en036qtEQKDTCEd4KIB0K4pJS6iYDv55hj779FfEZIpX4fZ5njLB5hLXSOZVSUDRfLCAf2m1JtWn07k78HjZ5EGuvCpCSmy9XIR0qp/IpfeJnhAyHGM3cnDdYMrv4I2oMDd1ro1VARkWoz7L8IThHeByREKCjlYSXfLlGQapKTsT7E//98=
  file: "mmc-develop-arm64.tar.gz"
  skip_cleanup: 'true'
  draft: true
  on:
    all_branches: true
    repo: JJTech0130/MultiMC5
